---
title: "1st_year_final_CBrennan"
author: "Caitriona Brennan PID: A59011982"
date: "6/28/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Importing data and saving as a variable:

```{r}
covid_data <- read.csv("covid-19-variant-data.csv")
head(covid_data)
```

Loading packages required to make plot:

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
library(scales)
library(gridExtra)
library(ggthemes)
```

Filtering out unwanted data:

```{r}
covid_data4 <- filter(covid_data, variant_name!="Total" & variant_name!='Other')
```

Converting "date" column to date format:

```{r}
covid_data4$date <- as.Date(covid_data4$date)
```

Making plot which uses one tick per month on x-axis. X-axis format is in "month-year".

```{r}
ggplot(covid_data4, aes(x = date, y=percentage, group=variant_name)) +
  geom_line(aes(color=variant_name)) +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
  scale_x_date(labels=date_format("%h-%y"), breaks=date_breaks("1 month")) +
  xlab("Data Source:<https://www.cdph.ca.gov/>") +
  ylab("Percentage of Sequenced Specimens") +
  ggtitle("Covid-19 Variants in California") +
  theme(axis.title.x=element_text(size=8, hjust = 1))
```
